### PR TITLE
Add gradle test task support

### PR DESCRIPTION
**Pull request by Theosakamg**
Test task support on colcon

### CODE REVIEW

**Comment by Theosakamg** [comment]
@esteve This PR is blocked by appveyor (not configured ?)
https://ci.appveyor.com/api/buildjobs/ut5k6bk4ro48au5h/log

**Comment by Theosakamg** [comment]
Fixed by #17

**Comment by Theosakamg** [comment]
@esteve rebased. Is everything ok ?

**Comment by esteve** [comment]
Thanks!

**Pull request merged**
