### PR TITLE
setup.cfg corrections. .rst -> .md, true -> True

### PR DESCRIPTION
**Pull request by calvertdw**

### CODE REVIEW

**Comment by calvertdw** [comment]
Looks like the same failures currently on master.

**Comment by Theosakamg** [comment]
_Fail linked to #17_

**Comment by esteve** [comment]
Thanks.

Why the change to ReST? Do you plan to add more documentation? All the ROS2 projects use Markdown, but I'm happy to switch to ReST if that's better.

The current value for `zip_safe` is valid. `setup.cfg` uses the INI format: https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.getboolean, so `true` seems to be fine (`True`, `1` and `on` are ok too)

**Comment by calvertdw** [comment]
@esteve I didn't switch to RST. The .cfg used to read ".rst" but I changed it to ".md".

P.S. Sorry I accidentally pushed status badges to this because I didn't use a branch.

**Comment by esteve** [comment]
Sorry, I didn't pay attention, I thought that you had renamed `README.md`, my fault.

No worries about the badges, thanks for adding them!

**Comment by esteve** [comment]
Thanks!

**Pull request merged**
