### PR TITLE
Fix source project path

### PR DESCRIPTION
**Pull request by Theosakamg**
Gradle can't find any source file (or build.gradle) in build directory.
It need to launch gradle in project sources code folder.

### CODE REVIEW

**Comment by esteve** [comment]
Do you mind pasting the error you get? I recall getting this working, so I'm wondering what went wrong.

**Comment by Theosakamg** [comment]
colcon seem to building the code on build folder (in colcon workspace) by `cwd=args.build_base` argument.
But the build.gradle and src has not available in this folder. If i switch on root project folder all work.
You can see in log folder in command.log and stdout_stderr.log

**Comment by esteve** [comment]
@Theosakamg I meant, if you could paste here the error you saw, at least to have some sort of traceability in the ticket. Also, could you rebase this PR instead of merging from master? It clutters the commit history. Thanks!

**Comment by Theosakamg** [comment]
@esteve rebase completed

from `rcljava_examples/stdout.log` :

```
<-------------> 0% INITIALIZING
FAILURE: Build failed with an exception.

* What went wrong:
Task 'assemble' not found in root project 'rcljava_examples'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.685 secs
```

**Comment by esteve** [comment]
This is no longer needed, I've copied the same code I wrote for `ament_java` and the source tree is copied to the build space before building. Thanks anyway.

**Pull request closed without merging**
