### PR TITLE
Ci support

### PR DESCRIPTION
**Pull request by Theosakamg**
Connected to #13

### CODE REVIEW

**Comment by esteve** [comment]
Thanks for joining the PRs. Could you rebase this PR against master? There's a couple of merge commits.

**Comment by Theosakamg** [comment]
@esteve can you squash this branch ?

**Comment by esteve** [comment]
Did you push? There are still two merge commits. Thanks.

**Comment by esteve** [comment]
Thanks! I've ended up squashing the commits.

**Pull request merged**
